blueprint:
  name: Automatic Lighting (Motion + Presence; Helper-Driven Durations)
  description: "Motion- and presence-activated lighting with multi-stage dimming controlled by helper entities."

  domain: automation

  input:
    motion_sensors:
      name: "Motion sensors"
      description: "Motion sensors (binary_sensor, device_class=motion)."
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    presence_sensors:
      name: "Presence / Occupancy sensors"
      description: "Optional binary_sensor presence/occupancy sensors; state 'on' means present."
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - occupancy
            - presence
          multiple: true

    presence_people:
      name: "People (person)"
      description: "Person entities; state 'home' means present."
      default: []
      selector:
        entity:
          domain: person
          multiple: true

    presence_trackers:
      name: "Device trackers"
      description: "Device_tracker entities; state 'home' means present."
      default: []
      selector:
        entity:
          domain: device_tracker
          multiple: true

    lights:
      name: "Lights to control"
      description: "Lights controlled by this automation."
      selector:
        entity:
          domain: light
          multiple: true

    auto_lighting_flag:
      name: "Master automatic lighting flag"
      description: "Must be ON for automation to run."
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flags:
      name: "Manual adjusted flags"
      description: "If ANY are ON, automation does NOT change the lights."
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    night_mode_flag:
      name: "Night mode"
      description: "When ON, light turns on instantly and uses Night Off timeout."
      selector:
        entity:
          domain: input_boolean

    occupied_brightness:
      name: "Occupied brightness"
      description: "Brightness value (0–100) for occupied state."
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: "Secondary brightness"
      description: "Brightness value for secondary stage."
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: "Third brightness"
      description: "Brightness value for third stage."
      selector:
        entity:
          domain: input_number

    secondary_minutes_helper:
      name: "Minutes to Secondary"
      description: "Minutes before switching to Secondary brightness."
      selector:
        entity:
          domain: input_number

    third_minutes_helper:
      name: "Minutes to Third"
      description: "Minutes before switching to Third brightness."
      selector:
        entity:
          domain: input_number

    off_minutes_helper:
      name: "Minutes to Off"
      description: "Minutes before final OFF stage."
      selector:
        entity:
          domain: input_number

    night_off_minutes:
      name: "Night minutes to Off"
      description: "Night mode OFF timeout (stages skipped)."
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    trans_occupied_day:
      name: "Transition: occupied (day)"
      description: "Transition when turning on normally."
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s

    trans_occupied_night:
      name: "Transition: occupied (night)"
      description: "Transition when turning on in night mode."
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s

    trans_dim_5m:
      name: "Transition: Secondary stage"
      description: "Transition when dimming to Secondary."
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s

    trans_dim_10m:
      name: "Transition: Third stage"
      description: "Transition when dimming to Third."
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s

    trans_off_night:
      name: "Transition: Night off"
      description: "Transition when turning off during night."
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s

    trans_off_final:
      name: "Transition: Final off"
      description: "Transition when turning lights fully off."
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s

mode: restart
max_exceeded: silent

# -------------------------
# Variables (Option A)
# -------------------------
variables:
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_secondary_brightness: !input secondary_brightness
  v_third_brightness: !input third_brightness
  v_night_mode_flag: !input night_mode_flag
  v_manual_adjust_flags: !input manual_adjust_flags

  v_motion: !input motion_sensors
  v_presence_bin: !input presence_sensors
  v_presence_people: !input presence_people
  v_presence_trackers: !input presence_trackers

  v_secondary_minutes_ent: !input secondary_minutes_helper
  v_third_minutes_ent: !input third_minutes_helper
  v_off_minutes_ent: !input off_minutes_helper
  v_night_off_minutes: !input night_off_minutes

  v_is_night: "{{ is_state(v_night_mode_flag, 'on') }}"

  v_timeout_secondary: >
    {% if v_is_night | bool %}00:00:00{% else %}
    {% set m = (states(v_secondary_minutes_ent) | float(0)) %}
    {{ "%02d:%02d:%02d"|format((m|int)//60, (m|int)%60, 0) }}
    {% endif %}

  v_timeout_third: >
    {% if v_is_night | bool %}00:00:00{% else %}
    {% set m = (states(v_third_minutes_ent) | float(0)) %}
    {{ "%02d:%02d:%02d"|format((m|int)//60, (m|int)%60, 0) }}
    {% endif %}

  v_timeout_off: >
    {% if v_is_night | bool %}
    {% set m = (v_night_off_minutes | int(0)) %}
    {% else %}
    {% set m = (states(v_off_minutes_ent) | float(0)) %}
    {% endif %}
    {{ "%02d:%02d:%02d"|format((m|int)//60, (m|int)%60, 0) }}

# -------------------------
# Triggers
# -------------------------
trigger:
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

  - id: presence_bin_on
    platform: state
    entity_id: !input presence_sensors
    to: "on"

  - id: presence_bin_off
    platform: state
    entity_id: !input presence_sensors
    to: "off"

  - id: person_home
    platform: state
    entity_id: !input presence_people
    to: "home"

  - id: person_away
    platform: state
    entity_id: !input presence_people
    to: "not_home"

  - id: tracker_home
    platform: state
    entity_id: !input presence_trackers
    to: "home"

  - id: tracker_away
    platform: state
    entity_id: !input presence_trackers
    to: "not_home"

  - id: night_mode_on
    platform: state
    entity_id: !input night_mode_flag
    to: "on"

  - id: night_mode_off
    platform: state
    entity_id: !input night_mode_flag
    to: "off"

# -------------------------
# Conditions
# -------------------------
condition:
  - condition: state
    entity_id: !input auto_lighting_flag
    state: "on"

  - condition: template
    value_template: "{{ expand(v_manual_adjust_flags) | selectattr('state','eq','on') | list | count == 0 }}"

# -------------------------
# Actions
# -------------------------
action:
  - choose:

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['motion_on','presence_bin_on','person_home','tracker_home'] }}
        sequence:
          - if:
              - condition: state
                entity_id: !input night_mode_flag
                state: "on"
            then:
              - service: light.turn_on
                target: { entity_id: !input lights }
                data:
                  transition: !input trans_occupied_night
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"
            else:
              - service: light.turn_on
                target: { entity_id: !input lights }
                data:
                  transition: !input trans_occupied_day
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['motion_off','presence_bin_off','person_away','tracker_away','night_mode_on','night_mode_off'] }}
        sequence:

          - condition: template
            value_template: >
              {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
              {% set active =
                   ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list
                   +
                   (ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list)
              %}
              {{ active | count == 0 }}

          - if:
              - condition: template
                value_template: "{{ v_is_night | bool }}"
            then:

              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target: { entity_id: !input lights }
                    data:
                      transition: !input trans_off_night

            else:

              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_secondary }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none and v_timeout_secondary != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target: { entity_id: !input lights }
                    data:
                      transition: !input trans_dim_5m
                      brightness_pct: "{{ states(v_secondary_brightness) | float }}"

              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_third }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none and v_timeout_third != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target: { entity_id: !input lights }
                    data:
                      transition: !input trans_dim_10m
                      brightness_pct: "{{ states(v_third_brightness) | float }}"

              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target: { entity_id: !input lights }
                    data:
                      transition: !input trans_off_final
