blueprint:
  name: Automatic Lighting (Motion + 4-Stage Dimming; Day/Evening Inputs + Manual Failsafe + Derived Dims)
  description: >
    Motion-activated lighting with 4-stage dimming and user-entered Day/Evening durations.
    - On motion: set occupied brightness (fast in normal, instant in night).
    - Normal (non-night) pipeline: Stage2 -> Stage3 -> Stage4 -> Off.
    - Stage brightness is derived from Occupied brightness:
        Stage2 = 3/4, Stage3 = 2/4, Stage4 = 1/4 of occupied.
    - Day vs Evening mode uses separate user-entered SECOND values for Stage2/3/4/Off.
    - Night mode skips dim stages and uses Night Off duration (seconds).
    - If ANY manual_adjust flags are ON, automation will NOT change lights on motion/mode,
      BUT will still enforce failsafe: turn OFF after X minutes of no motion.

  domain: automation

  input:
    # Sensors & lights
    motion_sensors:
      name: Motion sensors
      description: One or more motion sensors (binary_sensor, device_class=motion)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    lights:
      name: Lights to control
      description: One or more light entities to control together
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: This must be ON for the automation to run
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flags:
      name: Manual adjusted flags (one or more)
      description: If ANY of these are ON, automation won't adjust on motion/mode—but WILL still enforce the no-motion failsafe off
      selector:
        entity:
          domain: input_boolean
          multiple: true

    # Mode flags
    night_mode_flag:
      name: Night mode boolean
      description: When ON, motion turns on lights instantly and no-motion uses Night Off duration (stages skipped)
      selector:
        entity:
          domain: input_boolean

    evening_mode_flag:
      name: Evening mode boolean
      description: When ON (and Night mode is OFF), use Evening second values for dimming/off pipeline
      selector:
        entity:
          domain: input_boolean

    # Brightness helper (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      description: input_number holding occupied brightness (0-100). Dim stages are derived from this value.
      selector:
        entity:
          domain: input_number

    # -------- Day durations (seconds) --------
    day_stage2_seconds:
      name: Day - seconds to Stage 2
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 300   # 5 minutes

    day_stage3_seconds:
      name: Day - seconds to Stage 3
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 600   # 10 minutes

    day_stage4_seconds:
      name: Day - seconds to Stage 4
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 900   # 15 minutes

    day_off_seconds:
      name: Day - seconds to Off
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 1200  # 20 minutes

    # -------- Evening durations (seconds) --------
    evening_stage2_seconds:
      name: Evening - seconds to Stage 2
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 180   # 3 minutes

    evening_stage3_seconds:
      name: Evening - seconds to Stage 3
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 360   # 6 minutes

    evening_stage4_seconds:
      name: Evening - seconds to Stage 4
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 540   # 9 minutes

    evening_off_seconds:
      name: Evening - seconds to Off
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 720   # 12 minutes

    # -------- Night off seconds (stages skipped at night) --------
    night_off_seconds:
      name: Night - seconds to Off
      description: Night no-motion timeout before turning OFF (stages are skipped at night)
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: s
          mode: slider
      default: 60

    # Manual override failsafe timeout (minutes) - unchanged
    manual_override_off_minutes:
      name: Manual override – minutes to Off
      description: When any manual_adjust flag is ON, turn lights OFF after this many minutes without motion
      selector:
        number:
          min: 1
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 60

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, day/evening normal)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_stage:
      name: Dimming Transition
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_final:
      name: Transition (final off)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

# -------------------------
# Variables for Jinja usage
# -------------------------
variables:
  # Entities
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_night_mode_flag: !input night_mode_flag
  v_evening_mode_flag: !input evening_mode_flag
  v_manual_adjust_flags: !input manual_adjust_flags

  # Plain numeric inputs (seconds)
  v_day_stage2_seconds: !input day_stage2_seconds
  v_day_stage3_seconds: !input day_stage3_seconds
  v_day_stage4_seconds: !input day_stage4_seconds
  v_day_off_seconds: !input day_off_seconds

  v_evening_stage2_seconds: !input evening_stage2_seconds
  v_evening_stage3_seconds: !input evening_stage3_seconds
  v_evening_stage4_seconds: !input evening_stage4_seconds
  v_evening_off_seconds: !input evening_off_seconds

  v_night_off_seconds: !input night_off_seconds

  # Manual override failsafe minutes and derived timeout string (unchanged)
  v_manual_override_off_minutes: !input manual_override_off_minutes
  v_manual_off_timeout: >
    {% set mi = (v_manual_override_off_minutes | int(60)) %}
    {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}

  # Convenience flags
  v_is_night: "{{ is_state(v_night_mode_flag, 'on') }}"
  v_is_evening: "{{ is_state(v_evening_mode_flag, 'on') }}"
  v_any_manual_on: "{{ expand(v_manual_adjust_flags) | selectattr('state','eq','on') | list | count > 0 }}"

  # Derived brightness stages from occupied brightness (clamped 0..100)
  v_occ_pct: >
    {% set occ = (states(v_occupied_brightness) | float(0)) %}
    {{ [0, [occ, 100] | min] | max }}

  # Stage 2/3/4 derived as quarters of occupied
  v_stage2_pct: >
    {% set occ = (states(v_occupied_brightness) | float(0)) %}
    {% set occ = [0, [occ, 100] | min] | max %}
    {{ (occ * 3 / 4) | round(0) }}

  v_stage3_pct: >
    {% set occ = (states(v_occupied_brightness) | float(0)) %}
    {% set occ = [0, [occ, 100] | min] | max %}
    {{ (occ * 2 / 4) | round(0) }}

  v_stage4_pct: >
    {% set occ = (states(v_occupied_brightness) | float(0)) %}
    {% set occ = [0, [occ, 100] | min] | max %}
    {{ (occ * 1 / 4) | round(0) }}

  # Select seconds based on Day vs Evening (Night handled separately)
  v_stage2_seconds: >
    {% if v_is_evening | bool %}
      {{ v_evening_stage2_seconds | int(0) }}
    {% else %}
      {{ v_day_stage2_seconds | int(0) }}
    {% endif %}

  v_stage3_seconds: >
    {% if v_is_evening | bool %}
      {{ v_evening_stage3_seconds | int(0) }}
    {% else %}
      {{ v_day_stage3_seconds | int(0) }}
    {% endif %}

  v_stage4_seconds: >
    {% if v_is_evening | bool %}
      {{ v_evening_stage4_seconds | int(0) }}
    {% else %}
      {{ v_day_stage4_seconds | int(0) }}
    {% endif %}

  v_off_seconds: >
    {% if v_is_evening | bool %}
      {{ v_evening_off_seconds | int(0) }}
    {% else %}
      {{ v_day_off_seconds | int(0) }}
    {% endif %}

  # Build HH:MM:SS strings from selected seconds (skip in night for stages)
  v_timeout_stage2: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set s = (v_stage2_seconds | int(0)) %}
      {% if s <= 0 %}
        00:00:00
      {% else %}
        {{ "%02d:%02d:%02d"|format(s // 3600, (s % 3600) // 60, s % 60) }}
      {% endif %}
    {% endif %}

  v_timeout_stage3: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set s = (v_stage3_seconds | int(0)) %}
      {% if s <= 0 %}
        00:00:00
      {% else %}
        {{ "%02d:%02d:%02d"|format(s // 3600, (s % 3600) // 60, s % 60) }}
      {% endif %}
    {% endif %}

  v_timeout_stage4: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set s = (v_stage4_seconds | int(0)) %}
      {% if s <= 0 %}
        00:00:00
      {% else %}
        {{ "%02d:%02d:%02d"|format(s // 3600, (s % 3600) // 60, s % 60) }}
      {% endif %}
    {% endif %}

  v_timeout_off: >
    {% if v_is_night | bool %}
      {% set s = (v_night_off_seconds | int(0)) %}
      {{ "%02d:%02d:%02d"|format(s // 3600, (s % 3600) // 60, s % 60) }}
    {% else %}
      {% set s = (v_off_seconds | int(0)) %}
      {{ "%02d:%02d:%02d"|format(s // 3600, (s % 3600) // 60, s % 60) }}
    {% endif %}

# -------------
# Triggers
# -------------
trigger:
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

  - id: night_mode_on
    platform: state
    entity_id: !input night_mode_flag
    to: "on"

  - id: night_mode_off
    platform: state
    entity_id: !input night_mode_flag
    to: "off"

  - id: evening_mode_on
    platform: state
    entity_id: !input evening_mode_flag
    to: "on"

  - id: evening_mode_off
    platform: state
    entity_id: !input evening_mode_flag
    to: "off"

# -------------
# Conditions
# -------------
condition:
  - condition: state
    entity_id: !input auto_lighting_flag
    state: "on"

# -------------
# Actions
# -------------
action:
  - choose:

      # --- Motion Detected (suppressed if manual flags are ON)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_on' and not (v_any_manual_on | bool) }}"
        sequence:
          - if:
              - condition: state
                entity_id: !input night_mode_flag
                state: "on"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_night
                  brightness_pct: "{{ v_occ_pct | float }}"
            else:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_day
                  brightness_pct: "{{ v_occ_pct | float }}"

      # --- Mode toggled (suppressed if manual flags are ON)
      # This exists to restart pending waits when mode changes.
      - conditions:
          - condition: template
            value_template: >
              {{ (trigger.id in ['night_mode_on','night_mode_off','evening_mode_on','evening_mode_off'])
                 and not (v_any_manual_on | bool) }}
        sequence:
          - choose: []

      # --- Motion became OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_off' }}"
        sequence:

          # -------- MANUAL FAILSAFE: when any manual flags are ON --------
          - if:
              - condition: template
                value_template: "{{ v_any_manual_on | bool }}"
            then:
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_manual_off_timeout }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_final

            else:

              # -------- NIGHT MODE: single timeout -> OFF (skip stages) --------
              - if:
                  - condition: template
                    value_template: "{{ v_is_night | bool }}"
                then:
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        to: "on"
                    timeout: "{{ v_timeout_off }}"
                    continue_on_timeout: true

                  - if:
                      - condition: template
                        value_template: "{{ wait.trigger is none }}"
                    then:
                      - service: light.turn_off
                        target:
                          entity_id: !input lights
                        data:
                          transition: !input trans_off_night

                else:

                  # -------- NORMAL: Stage2 -> Stage3 -> Stage4 -> Off --------

                  # Wait until Stage 2 timeout (or cancel on motion)
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        to: "on"
                    timeout: "{{ v_timeout_stage2 }}"
                    continue_on_timeout: true

                  - if:
                      - condition: template
                        value_template: "{{ wait.trigger is none and v_timeout_stage2 != '00:00:00' }}"
                    then:
                      - service: light.turn_on
                        target:
                          entity_id: !input lights
                        data:
                          transition: !input trans_dim_stage
                          brightness_pct: "{{ v_stage2_pct | float }}"

                  # Wait until Stage 3 timeout (or cancel on motion)
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        to: "on"
                    timeout: "{{ v_timeout_stage3 }}"
                    continue_on_timeout: true

                  - if:
                      - condition: template
                        value_template: "{{ wait.trigger is none and v_timeout_stage3 != '00:00:00' }}"
                    then:
                      - service: light.turn_on
                        target:
                          entity_id: !input lights
                        data:
                          transition: !input trans_dim_stage
                          brightness_pct: "{{ v_stage3_pct | float }}"

                  # Wait until Stage 4 timeout (or cancel on motion)
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        to: "on"
                    timeout: "{{ v_timeout_stage4 }}"
                    continue_on_timeout: true

                  - if:
                      - condition: template
                        value_template: "{{ wait.trigger is none and v_timeout_stage4 != '00:00:00' }}"
                    then:
                      - service: light.turn_on
                        target:
                          entity_id: !input lights
                        data:
                          transition: !input trans_dim_stage
                          brightness_pct: "{{ v_stage4_pct | float }}"

                  # Final wait until Off timeout (or cancel on motion)
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input motion_sensors
                        to: "on"
                    timeout: "{{ v_timeout_off }}"
                    continue_on_timeout: true

                  - if:
                      - condition: template
                        value_template: "{{ wait.trigger is none }}"
                    then:
                      - service: light.turn_off
                        target:
                          entity_id: !input lights
                        data:
                          transition: !input trans_off_final
