blueprint:
  name: Automatic Lighting (Motion + Multi-Stage Dimming; Helper-Driven Durations)
  description: >
    Motion-activated lighting with multi-stage dimming controlled entirely by helper entities.
    - On motion: set occupied brightness (fast in normal, instant in night).
    - Night mode: no-motion uses a dedicated "night off" timeout, skipping dim stages.
    - No-motion stages (Secondary -> Third -> Off) are driven by input_number helpers.
    - Requires automatic_lighting ON and ALL selected manual_adjust flags OFF to run.
  domain: automation

  input:
    # Sensors & lights
    motion_sensors:
      name: Motion sensors
      description: One or more motion sensors (binary_sensor, device_class=motion)
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    lights:
      name: Lights to control
      description: One or more light entities to control together
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: This must be ON for the automation to run
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flags:
      name: Manual adjusted flags (one or more)
      description: If ANY of these are ON, the automation will NOT change the lights
      selector:
        entity:
          domain: input_boolean
          multiple: true

    # Night mode (only remaining mode)
    night_mode_flag:
      name: Night mode boolean
      description: When ON, motion turns on lights instantly and no-motion uses Night Off duration (stages skipped)
      selector:
        entity:
          domain: input_boolean

    # Brightness helpers (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: Secondary brightness helper
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: Third brightness helper
      selector:
        entity:
          domain: input_number

    # -------- Duration helpers (entity selectors; values are MINUTES) --------
    # Shared for all non-night cases
    secondary_minutes_helper:
      name: Minutes to Secondary (Helper)
      description: input_number entity whose value (in minutes) controls the first dim stage
      selector:
        entity:
          domain: input_number

    third_minutes_helper:
      name: Minutes to Third (Helper)
      description: input_number entity whose value (in minutes) controls the second dim stage
      selector:
        entity:
          domain: input_number

    off_minutes_helper:
      name: Minutes to Off (Helper)
      description: input_number entity whose value (in minutes) controls the final off stage
      selector:
        entity:
          domain: input_number

    # Night profile: usually a quick off; stages are skipped at night
    night_off_minutes:
      name: Night - minutes to Off
      description: Night no-motion timeout before turning OFF (stages are skipped at night)
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, normal)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_5m:
      name: Transition (to secondary stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_10m:
      name: Transition (to third stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_final:
      name: Transition (final off)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

# -------------------------
# Variables for Jinja usage
# -------------------------
variables:
  # Entities
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_secondary_brightness: !input secondary_brightness
  v_third_brightness: !input third_brightness
  v_night_mode_flag: !input night_mode_flag
  v_manual_adjust_flags: !input manual_adjust_flags

  # Duration helpers (entity references)
  v_secondary_minutes_ent: !input secondary_minutes_helper
  v_third_minutes_ent: !input third_minutes_helper
  v_off_minutes_ent: !input off_minutes_helper

  # Night off minutes (plain number input)
  v_night_off_minutes: !input night_off_minutes

  # Convenience flag
  v_is_night: "{{ is_state(v_night_mode_flag, 'on') }}"

  # Build HH:MM:SS strings from minute helpers
  v_timeout_secondary: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set m = (states(v_secondary_minutes_ent) | float(0)) %}
      {% if m <= 0 %}
        00:00:00
      {% else %}
        {% set mi = m | int %}
        {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}
      {% endif %}
    {% endif %}

  v_timeout_third: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set m = (states(v_third_minutes_ent) | float(0)) %}
      {% if m <= 0 %}
        00:00:00
      {% else %}
        {% set mi = m | int %}
        {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}
      {% endif %}
    {% endif %}

  v_timeout_off: >
    {% if v_is_night | bool %}
      {% set mi = (v_night_off_minutes | int(0)) %}
    {% else %}
      {% set m = (states(v_off_minutes_ent) | float(0)) %}
      {% set mi = m | int %}
    {% endif %}
    {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}

# -------------
# Triggers
# -------------
trigger:
  # Motion became ON
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  # Motion became OFF (start staged pipeline based on helpers)
  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

  # Night mode toggles — restart pending waits when mode changes
  - id: night_mode_on
    platform: state
    entity_id: !input night_mode_flag
    to: "on"

  - id: night_mode_off
    platform: state
    entity_id: !input night_mode_flag
    to: "off"

# -------------
# Conditions
# -------------
condition:
  - condition: state
    entity_id: !input auto_lighting_flag
    state: "on"

  # If ANY manual adjust flag is ON, block automation changes
  - condition: template
    value_template: >
      {{ expand(v_manual_adjust_flags) | selectattr('state','eq','on') | list | count == 0 }}

# -------------
# Actions
# -------------
action:
  - choose:

      # --- Motion Detected
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_on' }}"
        sequence:
          - if:
              - condition: state
                entity_id: !input night_mode_flag
                state: "on"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_night
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"
            else:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_day
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"

      # --- Motion became OFF: staged pipeline driven by helper entities
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_off' }}"
        sequence:

          # -------- NIGHT MODE: single timeout -> OFF (skip stages) --------
          - if:
              - condition: template
                value_template: "{{ v_is_night | bool }}"
            then:
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_night

            else:

              # -------- NORMAL: Secondary -> Third -> Off --------

              # Wait until Secondary timeout (or cancel on motion)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_secondary }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none and v_timeout_secondary != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_5m
                      brightness_pct: "{{ states(v_secondary_brightness) | float }}"

              # Wait until Third timeout (or cancel on motion)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_third }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none and v_timeout_third != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_10m
                      brightness_pct: "{{ states(v_third_brightness) | float }}"

              # Final wait until Off timeout (or cancel on motion)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_final
