blueprint:
  name: Automatic Lighting (Motion + Presence in one field; Helper-Driven Durations)
  description: >
    Motion- and presence-activated lighting with multi-stage dimming controlled by helper entities.
    - A single 'Motion sensors' input accepts motion, occupancy/presence binary_sensors, person, and device_tracker.
    - On activity (motion/presence): set occupied brightness (fast normal, instant at night).
    - Night mode: uses a dedicated off timeout and skips dimming stages.
    - No-activity pipeline: Secondary -> Third -> Off (minutes via helpers).
    - Requires automatic_lighting ON and ALL selected manual_adjust flags OFF to run.
  domain: automation

  input:
    # Activity sensors (merged): motion + presence in one field
    motion_sensors:
      name: Motion / Presence sensors
      description: >
        Select any combination of:
        - binary_sensor with device_class 'motion', 'occupancy', or 'presence' (use states 'on'/'off')
        - person (state 'home'/'not_home')
        - device_tracker (state 'home'/'not_home')
      selector:
        entity:
          # Allow multiple domains in a single input
          domain:
            - binary_sensor
            - person
            - device_tracker
          device_class:
            # This filter applies when the selected domain is binary_sensor
            - motion
            - occupancy
            - presence
          multiple: true

    # Lights
    lights:
      name: Lights to control
      description: One or more light entities to control together
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: This must be ON for the automation to run
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flags:
      name: Manual adjusted flags (one or more)
      description: If ANY of these are ON, the automation will NOT change the lights
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    # Night mode
    night_mode_flag:
      name: Night mode boolean
      description: When ON, activity turns on lights instantly and no-activity uses Night Off duration (stages skipped)
      selector:
        entity:
          domain: input_boolean

    # Brightness helpers (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: Secondary brightness helper
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: Third brightness helper
      selector:
        entity:
          domain: input_number

    # -------- Duration helpers (entity selectors; values are MINUTES) --------
    # Shared for all non-night cases
    secondary_minutes_helper:
      name: Minutes to Secondary (Helper)
      description: input_number entity whose value (in minutes) controls the first dim stage
      selector:
        entity:
          domain: input_number

    third_minutes_helper:
      name: Minutes to Third (Helper)
      description: input_number entity whose value (in minutes) controls the second dim stage
      selector:
        entity:
          domain: input_number

    off_minutes_helper:
      name: Minutes to Off (Helper)
      description: input_number entity whose value (in minutes) controls the final off stage
      selector:
        entity:
          domain: input_number

    # Night profile: usually a quick off; stages are skipped at night
    night_off_minutes:
      name: Night - minutes to Off
      description: Night no-activity timeout before turning OFF (stages are skipped at night)
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, normal)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_5m:
      name: Transition (to secondary stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_10m:
      name: Transition (to third stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_final:
      name: Transition (final off)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

# -------------------------
# Variables for Jinja usage (Option A)
# -------------------------
variables:
  # Entities
  v_activity_entities: !input motion_sensors
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_secondary_brightness: !input secondary_brightness
  v_third_brightness: !input third_brightness
  v_night_mode_flag: !input night_mode_flag
  v_manual_adjust_flags: !input manual_adjust_flags

  # Duration helpers (entity references)
  v_secondary_minutes_ent: !input secondary_minutes_helper
  v_third_minutes_ent: !input third_minutes_helper
