blueprint:
  name: Automatic Lighting (Motion + Multi-Stage Dimming; Mode-Aware Durations)
  description: >
    Motion-activated lighting with multi-stage dimming and mode awareness.
    - On motion: set occupied brightness (fast in day, instant in night).
    - Night mode: no-motion uses a dedicated "night off" timeout, skipping dim stages.
    - Day/Rest modes: no-motion stages -> Secondary -> Third -> Off, each driven by helpers.
    - Rest mode: if enabled while lights are on, set to secondary brightness immediately.
    - All no-motion timeouts are taken from input_number helpers so they can vary by mode.
    - Requires automatic_lighting ON and manual_adjusted OFF to run.
  domain: automation

  input:
    # Sensors & lights
    motion_sensors:
      name: Motion sensors
      description: One or more motion sensors (binary_sensor, device_class=motion)
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    lights:
      name: Lights to control
      description: One or more light entities to control together
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: This must be ON for the automation to run
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flag:
      name: Manual adjusted flag
      description: When this is ON, automation will NOT change the lights
      selector:
        entity:
          domain: input_boolean

    # Modes
    day_mode_flag:
      name: Day mode boolean
      description: When ON, no-motion durations follow the Day profile
      selector:
        entity:
          domain: input_boolean

    night_mode_flag:
      name: Night mode boolean
      description: When ON, motion turns on lights instantly and no-motion uses Night Off duration
      selector:
        entity:
          domain: input_boolean

    rest_mode_flag:
      name: Rest mode boolean
      description: When ON, durations follow the Rest profile; if toggled on while lights are already on, set to secondary brightness
      selector:
        entity:
          domain: input_boolean

    # Brightness helpers (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: Secondary brightness helper
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: Third brightness helper
      selector:
        entity:
          domain: input_number

    # -------- Duration helpers (in MINUTES) --------
    # Day profile: staged dimming to secondary -> third -> off
    day_secondary_minutes:
      name: Day - minutes to Secondary
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 5

    day_third_minutes:
      name: Day - minutes to Third
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 10

    day_off_minutes:
      name: Day - minutes to Off
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 15

    # Night profile: usually a quick off; skip secondary/third stages
    night_off_minutes:
      name: Night - minutes to Off
      description: Night no-motion timeout before turning OFF (stages are skipped at night)
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    # Rest profile: staged dimming to secondary -> third -> off
    rest_secondary_minutes:
      name: Rest - minutes to Secondary
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 5

    rest_third_minutes:
      name: Rest - minutes to Third
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 10

    rest_off_minutes:
      name: Rest - minutes to Off
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 15

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, day)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_5m:
      name: Transition (to secondary stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_10m:
      name: Transition (to third stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_final:
      name: Transition (final off)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

# -------------------------
# Variables for Jinja usage
# -------------------------
variables:
  # Entities
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_secondary_brightness: !input secondary_brightness
  v_third_brightness: !input third_brightness
  v_day_mode_flag: !input day_mode_flag
  v_night_mode_flag: !input night_mode_flag
  v_rest_mode_flag: !input rest_mode_flag

  # Duration helpers (entity references)
  v_day_secondary_minutes: !input day_secondary_minutes
  v_day_third_minutes: !input day_third_minutes
  v_day_off_minutes: !input day_off_minutes
  v_night_off_minutes: !input night_off_minutes
  v_rest_secondary_minutes: !input rest_secondary_minutes
  v_rest_third_minutes: !input rest_third_minutes
  v_rest_off_minutes: !input rest_off_minutes

  # Helper to compute current mode name with precedence: Rest > Night > Day > default Day
  v_mode: >
    {% if is_state(v_rest_mode_flag, 'on') %}
      rest
    {% elif is_state(v_night_mode_flag, 'on') %}
      night
    {% elif is_state(v_day_mode_flag, 'on') %}
      day
    {% else %}
      day
    {% endif %}

  # Build HH:MM:SS strings from minute helpers for the active mode
  v_timeout_secondary: >
    {% set minutes =
      (states(v_rest_mode_flag) == 'on') * (states(v_rest_secondary_minutes) | int) +
      (states(v_rest_mode_flag) != 'on' and states(v_night_mode_flag) != 'on') * (states(v_day_secondary_minutes) | int)
    %}
    {# For night we do not use secondary; produce 00:00:00 (skipped) #}
    {% if v_mode == 'night' %}
      00:00:00
    {% else %}
      {% set m = minutes | int %}
      {{ "%02d:%02d:%02d"|format(m // 60, m % 60, 0) }}
    {% endif %}

  v_timeout_third: >
    {% set minutes =
      (states(v_rest_mode_flag) == 'on') * (states(v_rest_third_minutes) | int) +
      (states(v_rest_mode_flag) != 'on' and states(v_night_mode_flag) != 'on') * (states(v_day_third_minutes) | int)
    %}
    {% if v_mode == 'night' %}
      00:00:00
    {% else %}
      {% set m = minutes | int %}
      {{ "%02d:%02d:%02d"|format(m // 60, m % 60, 0) }}
    {% endif %}

  v_timeout_off: >
    {% if v_mode == 'night' %}
      {% set m = (states(v_night_off_minutes) | int) %}
    {% elif v_mode == 'rest' %}
      {% set m = (states(v_rest_off_minutes) | int) %}
    {% else %}
      {% set m = (states(v_day_off_minutes) | int) %}
    {% endif %}
    {{ "%02d:%02d:%02d"|format(m // 60, m % 60, 0) }}

# -------------
# Triggers
# -------------
trigger:
  # Motion became ON
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"

  # Motion became OFF (start staged pipeline based on mode helpers)
  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

  # Mode toggles — included so pending waits are restarted when modes change
  - id: day_mode_on
    platform: state
    entity_id: !input day_mode_flag
    to: "on"

  - id: day_mode_off
    platform: state
    entity_id: !input day_mode_flag
    to: "off"

  - id: night_mode_on
    platform: state
    entity_id: !input night_mode_flag
    to: "on"

  - id: night_mode_off
    platform: state
    entity_id: !input night_mode_flag
    to: "off"

  - id: rest_mode_on
    platform: state
    entity_id: !input rest_mode_flag
    to: "on"

  - id: rest_mode_off
    platform: state
    entity_id: !input rest_mode_flag
    to: "off"

# -------------
# Conditions
# -------------
condition:
  - condition: state
    entity_id: !input auto_lighting_flag
    state: "on"
  - condition: state
    entity_id: !input manual_adjust_flag
    state: "off"

# -------------
# Actions
# -------------
action:
  - choose:

      # --- Rest Mode toggled ON: if any target light is already on, set to Secondary brightness
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'rest_mode_on' }}"
          - condition: template
            value_template: "{{ expand(v_lights) | selectattr('state','eq','on') | list | count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input lights
            data:
              transition: 5
              brightness_pct: "{{ states(v_secondary_brightness) | float }}"

      # --- Motion Detected
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_on' }}"
        sequence:
          - if:
              - condition: state
                entity_id: !input night_mode_flag
                state: "on"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_night
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"
            else:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_day
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"

      # --- Motion became OFF: staged pipeline driven by per-mode helpers
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'motion_off' }}"
        sequence:

          # -------- NIGHT MODE: single timeout -> OFF (skip stages) --------
          - if:
              - condition: template
                value_template: "{{ v_mode == 'night' }}"
            then:
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_night

            else:

              # -------- DAY or REST MODE: Secondary -> Third -> Off --------

              # Wait until Secondary timeout (or cancel on motion)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_secondary }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none and v_timeout_secondary != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_5m
                      brightness_pct: "{{ states(v_secondary_brightness) | float }}"

              # Wait until Third timeout (or cancel on motion)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_third }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none and v_timeout_third != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_10m
                      brightness_pct: "{{ states(v_third_brightness) | float }}"

              # Final wait until Off timeout (or cancel on motion)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_final
