blueprint:
  name: Automatic Lighting (Motion + Presence; Helper-Driven Durations)
  description: >
    Motion- and presence-activated lighting with multi-stage dimming controlled by helper entities.
    - Motion: binary_sensor (device_class=motion)
    - Presence: binary_sensor (device_class=occupancy/presence), person, device_tracker, and Presence Devices (device registry)
    - On activity (motion/presence entities): set occupied brightness (fast normal, instant at night).
    - Night mode: uses a dedicated off timeout and skips dimming stages.
    - No-activity pipeline: Secondary -> Third -> Off (minutes via helpers).
    - Presence Devices participate in activity detection for waits/inactivity checks (via device_entities()),
      but cannot act as direct triggers; include entities in presence fields to trigger "on".
    - Requires automatic_lighting ON and ALL selected manual_adjust flags OFF to run.
  domain: automation

  input:
    # Motion sensors (STRICT: device_class motion)
    motion_sensors:
      name: Motion sensors
      description: One or more motion sensors (binary_sensor, device_class=motion)
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    # Presence (binary_sensor presence/occupancy) - optional
    presence_sensors:
      name: Presence / Occupancy sensors
      description: Optional: binary_sensor presence/occupancy sensors that mean "someone is here"
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - occupancy
            - presence
          multiple: true

    # People presence (person) - optional
    presence_people:
      name: People (person)
      description: Optional: person entities; state 'home' means present
      default: []
      selector:
        entity:
          domain: person
          multiple: true

    # Device trackers presence (device_tracker) - optional
    presence_trackers:
      name: Device trackers
      description: Optional: device_tracker entities; state 'home' means present
      default: []
      selector:
        entity:
          domain: device_tracker
          multiple: true

    # NEW: Presence devices (Device Registry selection) - optional
    presence_devices:
      name: Presence devices (device registry)
      description: >
        Optional: select devices whose entities imply presence (e.g., phones with device_tracker,
        presence/occupancy sensors). These devices are used to detect activity during waits and to
        block the inactivity pipeline. NOTE: Devices cannot be used directly as triggers; add their
        entities above if you want "on/home" to turn on lights.
      default: []
      selector:
        device:
          multiple: true

    # Lights
    lights:
      name: Lights to control
      description: One or more light entities to control together
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: This must be ON for the automation to run
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flags:
      name: Manual adjusted flags (one or more)
      description: If ANY of these are ON, the automation will NOT change the lights
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    # Night mode
    night_mode_flag:
      name: Night mode boolean
      description: When ON, activity turns on lights instantly and no-activity uses Night Off duration (stages skipped)
      selector:
        entity:
          domain: input_boolean

    # Brightness helpers (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: Secondary brightness helper
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: Third brightness helper
      selector:
        entity:
          domain: input_number

    # -------- Duration helpers (entity selectors; values are MINUTES) --------
    # Shared for all non-night cases
    secondary_minutes_helper:
      name: Minutes to Secondary (Helper)
      description: input_number entity whose value (in minutes) controls the first dim stage
      selector:
        entity:
          domain: input_number

    third_minutes_helper:
      name: Minutes to Third (Helper)
      description: input_number entity whose value (in minutes) controls the second dim stage
      selector:
        entity:
          domain: input_number

    off_minutes_helper:
      name: Minutes to Off (Helper)
      description: input_number entity whose value (in minutes) controls the final off stage
      selector:
        entity:
          domain: input_number

    # Night profile: usually a quick off; stages are skipped at night
    night_off_minutes:
      name: Night - minutes to Off
      description: Night no-activity timeout before turning OFF (stages are skipped at night)
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, normal)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_5m:
      name: Transition (to secondary stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_10m:
      name: Transition (to third stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_final:
      name: Transition (final off)
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

# -------------------------
# Variables for Jinja usage (Option A)
# -------------------------
variables:
  # Entities
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_secondary_brightness: !input secondary_brightness
  v_third_brightness: !input third_brightness
  v_night_mode_flag: !input night_mode_flag
  v_manual_adjust_flags: !input manual_adjust_flags

  # Sensor groups
  v_motion: !input motion_sensors
  v_presence_bin: !input presence_sensors
  v_presence_people: !input presence_people
  v_presence_trackers: !input presence_trackers

  # NEW: Presence devices (device ids)
  v_presence_devices: !input presence_devices

  # Duration helpers (entity references)
  v_secondary_minutes_ent: !input secondary_minutes_helper
  v_third_minutes_ent: !input third_minutes_helper
  v_off_minutes_ent: !input off_minutes_helper

  # Night off minutes (plain number input)
  v_night_off_minutes: !input night_off_minutes

  # Convenience flag
  v_is_night: "{{ is_state(v_night_mode_flag, 'on') }}"

  # Build HH:MM:SS strings from minute helpers
  v_timeout_secondary: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set m = (states(v_secondary_minutes_ent) | float(0)) %}
      {% if m <= 0 %}
        00:00:00
      {% else %}
        {% set mi = m | int %}
        {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}
      {% endif %}
    {% endif %}

  v_timeout_third: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set m = (states(v_third_minutes_ent) | float(0)) %}
      {% if m <= 0 %}
        00:00:00
      {% else %}
        {% set mi = m | int %}
        {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}
      {% endif %}
    {% endif %}

  v_timeout_off: >
    {% if v_is_night | bool %}
      {% set mi = (v_night_off_minutes | int(0)) %}
    {% else %}
      {% set m = (states(v_off_minutes_ent) | float(0)) %}
      {% set mi = m | int %}
    {% endif %}
    {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}

# -------------
# Triggers (entity-based)
# -------------
trigger:
  # Motion ON/OFF
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"
  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

  # Presence binary sensors ON/OFF
  - id: presence_bin_on
    platform: state
    entity_id: !input presence_sensors
    to: "on"
  - id: presence_bin_off
    platform: state
    entity_id: !input presence_sensors
    to: "off"

  # Person home/away
  - id: person_home
    platform: state
    entity_id: !input presence_people
    to: "home"
  - id: person_away
    platform: state
    entity_id: !input presence_people
    to: "not_home"

  # Device tracker home/away
  - id: tracker_home
    platform: state
    entity_id: !input presence_trackers
    to: "home"
  - id: tracker_away
    platform: state
    entity_id: !input presence_trackers
    to: "not_home"

  # Night mode toggles
  - id: night_mode_on
    platform: state
    entity_id: !input night_mode_flag
    to: "on"
  - id: night_mode_off
    platform: state
    entity_id: !input night_mode_flag
    to: "off"

# -------------
# Conditions (global gates)
# -------------
condition:
  - condition: state
    entity_id: !input auto_lighting_flag
    state: "on"

  # If ANY manual adjust flag is ON, block automation changes
  - condition: template
    value_template: >
      {{ expand(v_manual_adjust_flags) | selectattr('state','eq','on') | list | count == 0 }}

# -------------
# Actions
# -------------
action:
  - choose:

      # --- Any "activity" (motion/presence ON or arrival home) -> Occupied brightness
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['motion_on','presence_bin_on','person_home','tracker_home'] }}
        sequence:
          - if:
              - condition: state
                entity_id: !input night_mode_flag
                state: "on"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_night
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"
            else:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_day
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"

      # --- Any "inactivity" (motion/presence OFF or away) OR night mode toggle -> staged pipeline
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.id in ['motion_off','presence_bin_off','person_away','tracker_away','night_mode_on','night_mode_off'] }}
        sequence:

          # Only proceed if ALL selected sources (entities + derived from devices) are inactive/away
          - condition: template
            value_template: >
              {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
              {% set dev_ents = [] %}
              {% for did in v_presence_devices %}
                {% set dev_ents = dev_ents + device_entities(did) %}
              {% endfor %}
              {% set all_ents = ents + expand(dev_ents) %}
              {% set active =
                   (all_ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list)
                   +
                   (all_ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list)
              %}
              {{ active | count == 0 }}

          # -------- NIGHT MODE: single timeout -> OFF (skip stages) --------
          - if:
              - condition: template
                value_template: "{{ v_is_night | bool }}"
            then:
              # Wait for any activity to resume (any entity from selections or devices becomes active/home)
              - wait_template: >
                  {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
                  {% set dev_ents = [] %}
                  {% for did in v_presence_devices %}
                    {% set dev_ents = dev_ents + device_entities(did) %}
                  {% endfor %}
                  {% set all_ents = ents + expand(dev_ents) %}
                  {% set bin_on = all_ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list %}
                  {% set home_on = all_ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list %}
                  {{ (bin_on | count) + (home_on | count) > 0 }}
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_night

            else:

              # -------- NORMAL: Secondary -> Third -> Off --------

              # Wait until Secondary timeout (or cancel on any activity ON/HOME)
              - wait_template: >
                  {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
                  {% set dev_ents = [] %}
                  {% for did in v_presence_devices %}
                    {% set dev_ents = dev_ents + device_entities(did) %}
                  {% endfor %}
                  {% set all_ents = ents + expand(dev_ents) %}
                  {% set bin_on = all_ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list %}
                  {% set home_on = all_ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list %}
                  {{ (bin_on | count) + (home_on | count) > 0 }}
                timeout: "{{ v_timeout_secondary }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ not wait.completed and v_timeout_secondary != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_5m
                      brightness_pct: "{{ states(v_secondary_brightness) | float }}"

              # Wait until Third timeout (or cancel on any activity ON/HOME)
              - wait_template: >
                  {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
                  {% set dev_ents = [] %}
                  {% for did in v_presence_devices %}
                    {% set dev_ents = dev_ents + device_entities(did) %}
                  {% endfor %}
                  {% set all_ents = ents + expand(dev_ents) %}
                  {% set bin_on = all_ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list %}
                  {% set home_on = all_ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list %}
                  {{ (bin_on | count) + (home_on | count) > 0 }}
                timeout: "{{ v_timeout_third }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ not wait.completed and v_timeout_third != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_10m
                      brightness_pct: "{{ states(v_third_brightness) | float }}"

              # Final wait until Off timeout (or cancel on any activity ON/HOME)
              - wait_template: >
                  {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
                  {% set dev_ents = [] %}
                  {% for did in v_presence_devices %}
                    {% set dev_ents = dev_ents + device_entities(did) %}
                  {% endfor %}
                  {% set all_ents = ents + expand(dev_ents) %}
                  {% set bin_on = all_ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list %}
                  {% set home_on = all_ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list %}
                  {{ (bin_on | count) + (home_on | count) > 0 }}
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_final
