blueprint:
  name: Automatic Lighting (Motion + Presence; Helper-Driven Durations)
  description: >
    Motion- and presence-activated lighting with multi-stage dimming controlled by helper entities.
    - Motion: binary_sensor (device_class=motion)
    - Presence: binary_sensor (device_class=occupancy/presence), person, device_tracker
    - On activity (motion/presence): set occupied brightness (fast normal, instant at night).
    - Night mode: uses a dedicated off timeout and skips dimming stages.
    - No-activity pipeline: Secondary -> Third -> Off (minutes via helpers).
    - Requires automatic_lighting ON and ALL selected manual_adjust flags OFF to run.
  domain: automation

  input:
    # Motion sensors (STRICT: device_class motion)
    motion_sensors:
      name: Motion sensors
      description: >
        One or more motion sensors (binary_sensor) with device_class=motion.
        These are the primary activity triggers for the space.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    # Presence (binary_sensor presence/occupancy) - optional
    presence_sensors:
      name: Presence / Occupancy sensors
      description: >
        Optional: binary_sensor presence/occupancy sensors that indicate someone is present.
        State 'on' means present; 'off' means not present.
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - occupancy
            - presence
          multiple: true

    # People presence (person) - optional
    presence_people:
      name: People (person)
      description: >
        Optional: person entities; state 'home' means present; 'not_home' means away.
      default: []
      selector:
        entity:
          domain: person
          multiple: true

    # Device trackers presence (device_tracker) - optional
    presence_trackers:
      name: Device trackers
      description: >
        Optional: device_tracker entities; state 'home' means present; 'not_home' means away.
      default: []
      selector:
        entity:
          domain: device_tracker
          multiple: true

    # Lights
    lights:
      name: Lights to control
      description: >
        One or more light entities to control together for this area.
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: >
        Must be ON for this automation to run. Acts as the global on/off switch.
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flags:
      name: Manual adjusted flags (one or more)
      description: >
        If ANY of these booleans are ON, the automation will NOT change the lights.
        Useful when scenes or manual tweaks should hold.
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true

    # Night mode
    night_mode_flag:
      name: Night mode boolean
      description: >
        When ON, activity turns on lights with a night transition and no-activity uses a
        single Night Off timeout (dimming stages are skipped).
      selector:
        entity:
          domain: input_boolean

    # Brightness helpers (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      description: >
        input_number helper for occupied brightness (0–100).
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: Secondary brightness helper
      description: >
        input_number helper for secondary stage brightness (0–100).
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: Third brightness helper
      description: >
        input_number helper for third stage brightness (0–100).
      selector:
        entity:
          domain: input_number

    # -------- Duration helpers (entity selectors; values are MINUTES) --------
    secondary_minutes_helper:
      name: Minutes to Secondary (Helper)
      description: >
        input_number entity whose value (in minutes) controls the first dim stage.
        Set to 0 to skip this stage.
      selector:
        entity:
          domain: input_number

    third_minutes_helper:
      name: Minutes to Third (Helper)
      description: >
        input_number entity whose value (in minutes) controls the second dim stage.
        Set to 0 to skip this stage.
      selector:
        entity:
          domain: input_number

    off_minutes_helper:
      name: Minutes to Off (Helper)
      description: >
        input_number entity whose value (in minutes) controls the final off stage.
      selector:
        entity:
          domain: input_number

    # Night profile: usually a quick off; stages are skipped at night
    night_off_minutes:
      name: Night - minutes to Off
      description: >
        Night no-activity timeout (in minutes) before turning OFF; dimming stages are skipped in Night mode.
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, normal)
      description: >
        Transition in seconds when turning on in normal mode.
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      description: >
        Transition in seconds when turning on in Night mode.
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_5m:
      name: Transition (to secondary stage)
      description: >
        Transition in seconds when dimming to the secondary stage.
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_10m:
      name: Transition (to third stage)
      description: >
        Transition in seconds when dimming to the third stage.
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      description: >
        Transition in seconds when turning off in Night mode.
      default: 20
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_final:
      name: Transition (final off)
      description: >
        Transition in seconds when turning off at the final stage.
      default: 10
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

mode: restart
max_exceeded: silent

# -------------------------
# Variables for Jinja usage (Option A)
# -------------------------
variables:
  # Entities
  v_lights: !input lights
  v_occupied_brightness: !input occupied_brightness
  v_secondary_brightness: !input secondary_brightness
  v_third_brightness: !input third_brightness
  v_night_mode_flag: !input night_mode_flag
  v_manual_adjust_flags: !input manual_adjust_flags

  # Sensor groups
  v_motion: !input motion_sensors
  v_presence_bin: !input presence_sensors
  v_presence_people: !input presence_people
  v_presence_trackers: !input presence_trackers

  # Duration helpers (entity references)
  v_secondary_minutes_ent: !input secondary_minutes_helper
  v_third_minutes_ent: !input third_minutes_helper
  v_off_minutes_ent: !input off_minutes_helper

  # Night off minutes (plain number input)
  v_night_off_minutes: !input night_off_minutes

  # Convenience flag
  v_is_night: "{{ is_state(v_night_mode_flag, 'on') }}"

  # Build HH:MM:SS strings from minute helpers
  v_timeout_secondary: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set m = (states(v_secondary_minutes_ent) | float(0)) %}
      {% if m <= 0 %}
        00:00:00
      {% else %}
        {% set mi = m | int %}
        {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}
      {% endif %}
    {% endif %}

  v_timeout_third: >
    {% if v_is_night | bool %}
      00:00:00
    {% else %}
      {% set m = (states(v_third_minutes_ent) | float(0)) %}
      {% if m <= 0 %}
        00:00:00
      {% else %}
        {% set mi = m | int %}
        {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}
      {% endif %}
    {% endif %}

  v_timeout_off: >
    {% if v_is_night | bool %}
      {% set mi = (v_night_off_minutes | int(0)) %}
    {% else %}
      {% set m = (states(v_off_minutes_ent) | float(0)) %}
      {% set mi = m | int %}
    {% endif %}
    {{ "%02d:%02d:%02d"|format(mi // 60, mi % 60, 0) }}

# -------------
# Triggers
# -------------
trigger:
  # Motion ON/OFF
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: "on"
  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: "off"

  # Presence binary sensors ON/OFF (presence/occupancy -> 'on'/'off')
  - id: presence_bin_on
    platform: state
    entity_id: !input presence_sensors
    to: "on"
  - id: presence_bin_off
    platform: state
    entity_id: !input presence_sensors
    to: "off"

  # Person ON/OFF (home/not_home)
  - id: person_home
    platform: state
    entity_id: !input presence_people
    to: "home"
  - id: person_away
    platform: state
    entity_id: !input presence_people
    to: "not_home"

  # Device tracker ON/OFF (home/not_home)
  - id: tracker_home
    platform: state
    entity_id: !input presence_trackers
    to: "home"
  - id: tracker_away
    platform: state
    entity_id: !input presence_trackers
    to: "not_home"

  # Night mode toggles — restart pending waits when mode changes
  - id: night_mode_on
    platform: state
    entity_id: !input night_mode_flag
    to: "on"
  - id: night_mode_off
    platform: state
    entity_id: !input night_mode_flag
    to: "off"

# -------------
# Conditions (global gates)
# -------------
condition:
  - condition: state
    entity_id: !input auto_lighting_flag
    state: "on"

  # If ANY manual adjust flag is ON, block automation changes
  - condition: template
    description: >
      Gate: if ANY manual adjust flag is ON, prevent automation changes.
    value_template: >
      {{ expand(v_manual_adjust_flags) | selectattr('state','eq','on') | list | count == 0 }}

# -------------
# Actions
# -------------
action:
  - choose:

      # --- Any "activity" (motion/presence ON or arrival home) -> Occupied brightness
      - conditions:
          - condition: template
            description: >
              Activity became ON/HOME (motion or presence).
            value_template: >
              {{ trigger.id in ['motion_on','presence_bin_on','person_home','tracker_home'] }}
        sequence:
          - if:
              - condition: state
                entity_id: !input night_mode_flag
                state: "on"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_night
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"
            else:
              - service: light.turn_on
                target:
                  entity_id: !input lights
                data:
                  transition: !input trans_occupied_day
                  brightness_pct: "{{ states(v_occupied_brightness) | float }}"

      # --- Any "inactivity" (motion/presence OFF or away) OR night mode toggle -> staged pipeline
      - conditions:
          - condition: template
            description: >
              Inactivity or Night mode toggle detected; consider starting staged pipeline.
            value_template: >
              {{ trigger.id in ['motion_off','presence_bin_off','person_away','tracker_away','night_mode_on','night_mode_off'] }}
        sequence:

          # Only proceed if ALL selected entities are inactive/away
          - condition: template
            description: >
              Start pipeline only when ALL activity sources are inactive/away.
            value_template: >
              {% set ents = expand(v_motion) + expand(v_presence_bin) + expand(v_presence_people) + expand(v_presence_trackers) %}
              {% set active =
                   ents | selectattr('domain','eq','binary_sensor') | selectattr('state','eq','on') | list
                   +
                   (ents | selectattr('domain','in',['person','device_tracker']) | selectattr('state','eq','home') | list)
              %}
              {{ active | count == 0 }}

          # -------- NIGHT MODE: single timeout -> OFF (skip stages) --------
          - if:
              - condition: template
                description: >
                  Night mode path.
                value_template: "{{ v_is_night | bool }}"
            then:
              # Wait for any activity to resume (motion OR presence goes active/home)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    description: >
                      Night timeout elapsed with no activity; turn off.
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_night

            else:

              # -------- NORMAL: Secondary -> Third -> Off --------

              # Wait until Secondary timeout (or cancel on any activity ON/HOME)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_secondary }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    description: >
                      Secondary timeout elapsed with no activity and stage enabled.
                    value_template: "{{ wait.trigger is none and v_timeout_secondary != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_5m
                      brightness_pct: "{{ states(v_secondary_brightness) | float }}"

              # Wait until Third timeout (or cancel on any activity ON/HOME)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_third }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    description: >
                      Third timeout elapsed with no activity and stage enabled.
                    value_template: "{{ wait.trigger is none and v_timeout_third != '00:00:00' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_dim_10m
                      brightness_pct: "{{ states(v_third_brightness) | float }}"

              # Final wait until Off timeout (or cancel on any activity ON/HOME)
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_sensors
                    to: "on"
                  - platform: state
                    entity_id: !input presence_people
                    to: "home"
                  - platform: state
                    entity_id: !input presence_trackers
                    to: "home"
                timeout: "{{ v_timeout_off }}"
                continue_on_timeout: true

              - if:
                  - condition: template
                    description: >
                      Final timeout elapsed with no activity; turn off.
                    value_template: "{{ wait.trigger is none }}"
                then:
                  - service: light.turn_off
                    target:
                      entity_id: !input lights
                    data:
                      transition: !input trans_off_final
