blueprint:
  name: Automatic Lighting (Motion + Multi-Stage Dimming; Helper-Driven Durations)
  description: >
    Motion-activated lighting with multi-stage dimming controlled entirely by helper entities.
    - On motion: set occupied brightness (fast in normal, instant in night).
    - Night mode: no-motion uses a dedicated "night off" timeout, skipping dim stages.
    - No-motion stages (Secondary -> Third -> Off) are driven by input_number helpers.
    - Requires automatic_lighting ON and manual_adjusted OFF to run.
  domain: automation

  input:
    # Sensors & lights
    motion_sensors:
      name: Motion sensors
      description: One or more motion sensors (binary_sensor, device_class=motion)
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true

    lights:
      name: Lights to control
      description: One or more light entities to control together
      selector:
        entity:
          domain: light
          multiple: true

    # Master gates
    auto_lighting_flag:
      name: Master automatic lighting boolean
      description: This must be ON for the automation to run
      selector:
        entity:
          domain: input_boolean

    manual_adjust_flag:
      name: Manual adjusted flag
      description: When this is ON, automation will NOT change the lights
      selector:
        entity:
          domain: input_boolean

    # Night mode (only remaining mode)
    night_mode_flag:
      name: Night mode boolean
      description: When ON, motion turns on lights instantly and no-motion uses Night Off duration (stages skipped)
      selector:
        entity:
          domain: input_boolean

    # Brightness helpers (0–100)
    occupied_brightness:
      name: Occupied brightness helper
      selector:
        entity:
          domain: input_number

    secondary_brightness:
      name: Secondary brightness helper
      selector:
        entity:
          domain: input_number

    third_brightness:
      name: Third brightness helper
      selector:
        entity:
          domain: input_number

    # -------- Duration helpers (entity selectors; values are MINUTES) --------
    # Shared for all non-night cases
    secondary_minutes_helper:
      name: Minutes to Secondary (Helper)
      description: input_number entity whose value (in minutes) controls the first dim stage
      selector:
        entity:
          domain: input_number

    third_minutes_helper:
      name: Minutes to Third (Helper)
      description: input_number entity whose value (in minutes) controls the second dim stage
      selector:
        entity:
          domain: input_number

    off_minutes_helper:
      name: Minutes to Off (Helper)
      description: input_number entity whose value (in minutes) controls the final off stage
      selector:
        entity:
          domain: input_number

    # Night profile: usually a quick off; stages are skipped at night
    night_off_minutes:
      name: Night - minutes to Off
      description: Night no-motion timeout before turning OFF (stages are skipped at night)
      selector:
        number:
          min: 0
          max: 240
          step: 1
          unit_of_measurement: min
          mode: slider
      default: 1

    # Transitions (seconds)
    trans_occupied_day:
      name: Transition (occupied, normal)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_occupied_night:
      name: Transition (occupied, night)
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_5m:
      name: Transition (to secondary stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_dim_10m:
      name: Transition (to third stage)
      default: 30
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: s
          mode: slider

    trans_off_night:
      name: Transition (off in Night mode)
      default: 20
      selector:
        number:
          min: 0
          max: 120
